---
- name: Include variables.
  include_vars: "vars/all.yml"
  tags: always

- name: Define mysql_user_name.
  set_fact:
    mysql_user_name: "{{ __mysql_user_name }}"
  when: mysql_user_name is not defined
  tags: always

- name: Define mysql_root_password.
  set_fact:
    mysql_root_password: "{{ __mysql_root_password }}"
  when: mysql_root_password is not defined
  tags: always

- name: Define ivrh_default_backup_user_username.
  set_fact:
    ivrh_default_backup_user_username: "{{ __ivrh_default_backup_user_username }}"
  when: ivrh_default_backup_user_username is not defined
  tags: always

- name: Define ivrh_mysql_backup_location.
  set_fact:
    ivrh_mysql_backup_location: "{{ __ivrh_mysql_backup_location }}"
  when: ivrh_mysql_backup_location is not defined
  tags: always

- name: Check if backup destination directory ivrh_mysql_backup_location already exist
  stat: path={{ ivrh_mysql_backup_location }}
  register: ivrh_mysql_backup_location_exists_path
  tags: always

- name: Define ivrh_mysql_daily_backup_location.
  set_fact:
    ivrh_mysql_daily_backup_location: "{{ __ivrh_mysql_daily_backup_location }}"
  when: ivrh_mysql_daily_backup_location is not defined
  tags: always

- name: Define ivrh_mysql_days_to_retain_backups_for.
  set_fact:
    ivrh_mysql_days_to_retain_backups_for: "{{ __ivrh_mysql_days_to_retain_backups_for }}"
  when: ivrh_mysql_days_to_retain_backups_for is not defined
  tags: always

- name: Define ivrh_source_backup_path.
  set_fact:
    ivrh_source_backup_path: "{{ __ivrh_source_backup_path }}"
  when: ivrh_source_backup_path is not defined
  tags: always

- name: Define ivrh_mysql_backup_script_location.
  set_fact:
    ivrh_mysql_backup_script_location: "{{ __ivrh_mysql_backup_script_location }}"
  when: ivrh_mysql_backup_script_location is not defined
  tags: always

- name: Define ivrh_website_backup_destination.
  set_fact:
    ivrh_website_backup_destination: "{{ __ivrh_website_backup_destination }}"
  when: ivrh_website_backup_destination is not defined
  tags: always

- name: Get mysqlbackup script
  template:
    src: "backupmysql.j2"
    dest: "{{ ivrh_mysql_backup_script_location }}"
    owner: root
    group: root
    mode: 0755
  tags:
    - setup

- name: Creates backup folder
  file: path={{ ivrh_mysql_backup_location }} state=directory owner={{ ivrh_default_backup_user_username }} group={{ ivrh_default_backup_user_username}} mode=0755 recurse=yes
  when: ivrh_mysql_backup_location_exists_path.stat.exists == false
  tags:
    - setup

- name: Creates daily backup folder
  file: path={{ ivrh_mysql_daily_backup_location }} state=directory owner={{ ivrh_default_backup_user_username }} group={{ ivrh_default_backup_user_username}} mode=0755 recurse=yes
  tags:
    - setup

- name: Creates website backup folder
  file: path={{ ivrh_website_backup_destination }} state=directory owner={{ ivrh_default_backup_user_username }} group={{ ivrh_default_backup_user_username}} mode=0755 recurse=yes
  tags:
    - setup

- name: Backup production database to hostname.sql
  command: "{{ ivrh_mysql_backup_script_location }} {{ ivrh_mysql_days_to_retain_backups_for }} {{ ivrh_mysql_backup_location }}/"
  when: ivrh_mysql_backup_location_exists_path.stat.exists
  become: yes
  become_user: "{{ ivrh_default_backup_user_username }}"
  tags:
    - execute
    - setup
- debug: msg="Backing all databases to {{ ivrh_mysql_backup_location }}"

- name: Check if backup source directory ivrh_source_backup_path already exist
  stat: path={{ ivrh_source_backup_path }}
  register: ivrh_source_backup_path_exists
  tags: always

- name: Check if backup destination directory ivrh_website_backup_destination already exist
  stat: path={{ ivrh_website_backup_destination }}
  register: ivrh_website_backup_destination_path
  tags: always

- name: Create easy to use copy of the file system
  command: "rsync -a {{ ivrh_delete_option_for_rsync }} {{ ivrh_source_backup_path }} {{ ivrh_website_backup_destination }}"
  when: ivrh_source_backup_path_exists.stat.exists
  tags:
    - execute
    - setup
- debug: msg="Backing up website files from {{ ivrh_source_backup_path }} to {{ ivrh_website_backup_destination }}"

- name: Check if backup destination directory ivrh_mysql_daily_backup_location already exist
  stat: path={{ ivrh_mysql_daily_backup_location }}
  register: ivrh_mysql_daily_backup_location_path
  tags: always

- name: Ensure cron job created for regular database backups
  cron:
    name: "MySQL Backup cron"
    minute: "3"
    hour: "1"
    job: "{{ ivrh_mysql_backup_script_location }} {{ ivrh_mysql_days_to_retain_backups_for }} {{ ivrh_mysql_daily_backup_location }}"
    user: "{{ ivrh_default_backup_user_username }}"
  when: ivrh_mysql_backup_script_location is defined and ivrh_mysql_days_to_retain_backups_for is defined and ivrh_mysql_daily_backup_location_path.stat.exists
  tags: setup

- name: Get mysqlbackup script
  template:
    src: "backupmysql.j2"
    dest: "{{ ivrh_mysql_backup_script_location }}"
    owner: root
    group: root
    mode: 0755
  when: ivrh_mysql_backup_script_location is defined
  tags: setup
